# docker-compose.yml
version: '3'

services:
  # Backend Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - chroma_data:/app/data/chroma
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_DB_PATH=/app/data/chroma
      - CHUNK_SIZE=512
      - CHUNK_OVERLAP=50
    restart: unless-stopped

  # Frontend Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:5000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data:
